name: Build
on: push

jobs:
  windows:
    name: Windows Build
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Install pkg
        run: npm install --global pkg
      - name: Build
        run: |
          pkg index.js --targets node16-win-x64
  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Install pkg
        run: npm install --global pkg
      - name: Build
        run: |
          ls -la
          pkg index.js --targets node16-linux-x64
  macos:
    name: MacOS Build
    runs-on: macos-latest
    defaults:
      run:
        working-directory: src
    steps:
      - name: Install pkg
        run: npm install --global pkg
      - name: Build
        run: |
          pkg index.js --targets node16-macos-x64